#	$Header: /cvsroot/posix2/posix2/tools/xinstall/Makefile,v 1.3 2000/08/26 09:22:52 amai Exp $

PROG=	install
SRCS=	../ls/stat_flags.c xinstall.c

DEFADD = -D_BSD_SOURCE

MAN=	install.1

#.PATH:	${.CURDIR}/../../bin/ls

#realinstall:
#	${INSTALL} ${INSTALL_COPY} ${INSTALL_STRIP} -o ${BINOWN} -g ${BINGRP} \
#	    -m ${BINMODE} ${PROG} ${DESTDIR}${BINDIR}/install

include ../tools.mk
