# $Header: /cvsroot/posix2/posix2/tools/ps/Makefile,v 1.2 2000/08/14 16:26:10 amai Exp $

PROG=	ps
SRCS=	fmt.c keyword.c nlist.c print.c ps.c
DPADD=	${LIBM} ${LIBKVM}
#LDADD=	-lm -lkvm
BINGRP=	kmem
BINMODE=2555

include ../tools.mk
