#$Header: /cvsroot/posix2/posix2/libext/libcom_err/Makefile,v 1.5 2000/08/18 19:17:47 amai Exp $

LIB=	com_err
SRCS=	com_err.c error_message.c et_name.c init_et.c

INC 	= ../include/
MKINC 	= ../../usr/share/mk/

HEADERS	= $(INC)com_err.h error_table.h
DEFADD	= -D_HAS_SYS_ERRLIST

include ../Ext.mk
