# $Header: /cvsroot/posix2/posix2/libext/libc/nls/Makefile,v 1.5 2000/11/25 16:33:35 arnd Exp $

SRCS =	catclose.c catgets.c catopen.c 

HEADERS=	$(INC)nl_types.h 

INC 	= ../../include/
MKINC 	= ../../../usr/share/mk/
  
include ../../Ext.mk
