#	$Header: /cvsroot/posix2/posix2/tools/hexdump/Makefile,v 1.2 2000/08/14 16:26:09 amai Exp $

PROG=	hexdump
SRCS=	conv.c display.c hexdump.c hexsyntax.c odsyntax.c parse.c
MAN=	hexdump.1 od.1
LINKS=	od

include ../tools.mk
