# $Header: /cvsroot/posix2/posix2/tools/patch/Makefile,v 1.3 2000/08/21 13:37:23 amai Exp $

PROG=	patch
SRCS=	patch.c pch.c inp.c version.c util.c backupfile.c
CLEANFILES= *.rej *.orig

include ../tools.mk

