#	$Header: /cvsroot/posix2/posix2/tools/man/Makefile,v 1.2 2000/08/14 16:26:10 amai Exp $

PROG=	man
SRCS=	config.c man.c
MAN=	man.1 man.conf.5 help.1

# LINKS=	${BINDIR}/man ${BINDIR}/help

include ../tools.mk
