#	$Header: /cvsroot/posix2/posix2/tools/talk/Makefile,v 1.2 2000/08/14 16:26:11 amai Exp $

PROG=	talk
DPADD=	${LIBCURSES}
LDADD=	-lcurses
SRCS=	ctl.c ctl_transact.c display.c get_addrs.c get_names.c \
	init_disp.c invite.c io.c look_up.c msgs.c talk.c

include ../tools.mk
