# $Header: /cvsroot/posix2/posix2/tools/rpcgen/Makefile,v 1.2 2000/11/17 19:17:34 arnd Exp $

PROG=	rpcgen
SRCS=	rpc_clntout.c rpc_cout.c rpc_hout.c rpc_main.c rpc_parse.c rpc_scan.c \
	rpc_svcout.c rpc_util.c rpc_sample.c rpc_tblout.c

include ../tools.mk

WFLAGS = -Wall -Wno-return-type -Wno-parentheses -Wno-unused -Wno-switch