# $Header: /cvsroot/posix2/posix2/libext/libutil/Makefile,v 1.2 2000/11/26 16:43:01 arnd Exp $

INC 	= ../include/
MKINC 	= ../../usr/share/mk/

LIB =	util
SRCS= fparseln.c getrawpartition.c uucplock.c
HDRS= $(INC)util.h

include ../ext.mk