#	$Header: /cvsroot/posix2/posix2/tools/m4/Makefile,v 1.2 2000/08/14 16:26:10 amai Exp $

# -DEXTENDED 
# 	if you want the paste & spaste macros.

PROG=	m4
SRCS=	eval.c expr.c look.c main.c misc.c gnum4.c
MAN=	m4.1

include ../tools.mk

CFLAGS+=-DEXTENDED
