# $Header: /cvsroot/posix2/posix2/tools/yacc/Makefile,v 1.2 2000/08/14 16:26:17 amai Exp $

PROG=	yacc
SRCS=	closure.c error.c lalr.c lr0.c main.c mkpar.c output.c reader.c \
	skeleton.c symtab.c verbose.c warshall.c
MAN=	yacc.1 yyfix.1

HEADERS= defs.h 
 
include ../tools.mk
