# $Header: /cvsroot/posix2/posix2/libext/libc/stdiox/Makefile,v 1.17 2000/11/26 16:43:01 arnd Exp $

INC         = ../../include/
MKINC       = ../../../usr/share/mk/

SRCS =	 perror.c popen.c rename.c setbuffer.c 
HEADERS= $(INC)stdio.h $(INC)sys/errnox.h 

include ../../Ext.mk
