#	$Header: /cvsroot/posix2/posix2/libext/libz/Makefile,v 1.5 2000/08/23 21:47:06 amai Exp $

LIB=	z

HDRS=	$(INC)zconf.h $(INC)zlib.h
SRCS=	adler32.c compress.c crc32.c deflate.c gzio.c infblock.c \
	infcodes.c inffast.c inflate.c inftrees.c infutil.c trees.c \
	uncompr.c zutil.c

INC 	= ../include/
MKINC 	= ../../usr/share/mk/

include ../Ext.mk
