#	$Header: /cvsroot/posix2/posix2/tools/shar/Makefile,v 1.2 2000/08/14 16:26:11 amai Exp $

MAN=	shar.1

beforeinstall:
	${INSTALL} ${INSTALL_COPY} -o ${BINOWN} -g ${BINGRP} -m ${BINMODE} \
	    ${.CURDIR}/shar.sh ${DESTDIR}/usr/bin/shar


include ../tools.mk
