# $Header: /cvsroot/posix2/posix2/libext/libc/stringx/Makefile,v 1.4 2000/11/25 16:33:35 arnd Exp $

INC 	= ../../include/
MKINC 	= ../../../usr/share/mk/

SRCS = strsep.c strxtens.c bm.c strlcpy.c strmode.c

HEADERS = $(INC)string.h

include ../../Ext.mk
