#	$Header: /cvsroot/posix2/posix2/tools/asa/Makefile,v 1.1 2000/09/11 01:15:12 arnd Exp $

PROG=	asa
SRC =	asa.c

LINKS=  fpr

include ../tools.mk

#LINKS=  ${BINDIR}/asa ${BINDIR}/fpr
#MLINKS= asa.1 fpr.1

#.include <bsd.prog.mk>
