#	from: @(#)Makefile	5.1 (Berkeley) 6/5/90
# $Header efile,v 1.2 1996/01/04 11:58:46 deraadt Exp $

# The BSD compatibility wrappers are in libc.
# However, an empty library must exist in case something tries to use it.

LIB=	compat

SRCS=nothing.c

#.include <bsd.lib.mk>

INC 	= ../include/
MKINC 	= ../../usr/share/mk/

include ../ext.mk